"""Analysis of results generated by the iterative round testing script"""

from __future__ import annotations

import json
from typing import List

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from core.core import decode_filename


def plot_price_rounds(encoded_files: List[str]):
    """
    Plots the price round graphs
    :param encoded_files: The list of the files
    """
    data = []
    for encoded_file in encoded_files:
        filename, model_name = decode_filename(encoded_file)
        with open(filename) as file:
            file_data = json.load(file)
            for pos, model_result in enumerate(file_data):
                for name, result in model_result.items():
                    data.append([pos, model_name, name, result['initial_cost'], result['price change'],
                                 result['total_iterations'], result['total_messages'], result['total money']])

    df = pd.DataFrame(data, columns=["Pos", "Model", "Name", "Initial cost", "Price Change", "Total Iterations",
                                     "Total Messages", "Total Money"])

    g = sns.FacetGrid(df, col='Model', sharex=False)
    g: sns.FacetGrid = (g.map(sns.barplot, "Total Iterations", "Name", ci=95).set_titles("{col_name}"))

    plt.show()


if __name__ == "__main__":
    september_20 = [
        "september_20/iterative_round_results_basic_j12_s2_0",
        "september_20/iterative_round_results_basic_j15_s2_0",
        "september_20/iterative_round_results_basic_j15_s3_0",
        "september_20/iterative_round_results_basic_j25_s5_0",
        "september_20/iterative_round_results_basic_j50_s5_0"
    ]

    plot_price_rounds(september_20)
